[tool.poetry]
name = "homework-14"
version = "0.1.0"
description = ""
authors = ["ilaavrumov <iliya200022@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
python-dotenv = "^1.0.1"
pandas = "^2.2.3"


[tool.poetry.group.dev.dependencies]
mypy = "^1.15.0"
black = "^25.1.0"
isort = "^6.0.0"
pytest = "^8.3.4"
lint = "^1.2.1"
flake8 = "^7.1.1"
pytest-cov = "^6.0.0"
requests = "^2.32.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
